export type Country = {
  iso: string;
  name: string;
  flag: string;
  dial: string;
};

export const COUNTRIES: Country[] = [
  { iso: "US", name: "United States", flag: "🇺🇸", dial: "1" },
  { iso: "CA", name: "Canada", flag: "🇨🇦", dial: "1" },
  { iso: "GB", name: "United Kingdom", flag: "🇬🇧", dial: "44" },
  { iso: "CN", name: "China", flag: "🇨🇳", dial: "86" },
  { iso: "JP", name: "Japan", flag: "🇯🇵", dial: "81" },
  { iso: "KR", name: "South Korea", flag: "🇰🇷", dial: "82" },
  { iso: "IN", name: "India", flag: "🇮🇳", dial: "91" },
  { iso: "AU", name: "Australia", flag: "🇦🇺", dial: "61" },
  { iso: "NZ", name: "New Zealand", flag: "🇳🇿", dial: "64" },
  { iso: "SG", name: "Singapore", flag: "🇸🇬", dial: "65" },
  { iso: "HK", name: "Hong Kong", flag: "🇭🇰", dial: "852" },
  { iso: "TW", name: "Taiwan", flag: "🇹🇼", dial: "886" },
  { iso: "MY", name: "Malaysia", flag: "🇲🇾", dial: "60" },
  { iso: "TH", name: "Thailand", flag: "🇹🇭", dial: "66" },
  { iso: "VN", name: "Vietnam", flag: "🇻🇳", dial: "84" },
  { iso: "ID", name: "Indonesia", flag: "🇮🇩", dial: "62" },
  { iso: "PH", name: "Philippines", flag: "🇵🇭", dial: "63" },
  { iso: "DE", name: "Germany", flag: "🇩🇪", dial: "49" },
  { iso: "FR", name: "France", flag: "🇫🇷", dial: "33" },
  { iso: "IT", name: "Italy", flag: "🇮🇹", dial: "39" },
  { iso: "ES", name: "Spain", flag: "🇪🇸", dial: "34" },
  { iso: "PT", name: "Portugal", flag: "🇵🇹", dial: "351" },
  { iso: "NL", name: "Netherlands", flag: "🇳🇱", dial: "31" },
  { iso: "BE", name: "Belgium", flag: "🇧🇪", dial: "32" },
  { iso: "CH", name: "Switzerland", flag: "🇨🇭", dial: "41" },
  { iso: "AT", name: "Austria", flag: "🇦🇹", dial: "43" },
  { iso: "SE", name: "Sweden", flag: "🇸🇪", dial: "46" },
  { iso: "NO", name: "Norway", flag: "🇳🇴", dial: "47" },
  { iso: "DK", name: "Denmark", flag: "🇩🇰", dial: "45" },
  { iso: "FI", name: "Finland", flag: "🇫🇮", dial: "358" },
  { iso: "IE", name: "Ireland", flag: "🇮🇪", dial: "353" },
  { iso: "PL", name: "Poland", flag: "🇵🇱", dial: "48" },
  { iso: "CZ", name: "Czech Republic", flag: "🇨🇿", dial: "420" },
  { iso: "GR", name: "Greece", flag: "🇬🇷", dial: "30" },
  { iso: "TR", name: "Turkey", flag: "🇹🇷", dial: "90" },
  { iso: "RU", name: "Russia", flag: "🇷🇺", dial: "7" },
  { iso: "UA", name: "Ukraine", flag: "🇺🇦", dial: "380" },
  { iso: "BR", name: "Brazil", flag: "🇧🇷", dial: "55" },
  { iso: "AR", name: "Argentina", flag: "🇦🇷", dial: "54" },
  { iso: "MX", name: "Mexico", flag: "🇲🇽", dial: "52" },
  { iso: "CL", name: "Chile", flag: "🇨🇱", dial: "56" },
  { iso: "CO", name: "Colombia", flag: "🇨🇴", dial: "57" },
  { iso: "AE", name: "UAE", flag: "🇦🇪", dial: "971" },
  { iso: "SA", name: "Saudi Arabia", flag: "🇸🇦", dial: "966" },
  { iso: "IL", name: "Israel", flag: "🇮🇱", dial: "972" },
  { iso: "ZA", name: "South Africa", flag: "🇿🇦", dial: "27" },
  { iso: "EG", name: "Egypt", flag: "🇪🇬", dial: "20" },
  { iso: "NG", name: "Nigeria", flag: "🇳🇬", dial: "234" },
  { iso: "KE", name: "Kenya", flag: "🇰🇪", dial: "254" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]!;
